# Team name aliases for fuzzy matching across data sources.
# Format: "Canonical Name": ["alias1", "alias2", ...]

football:
  # EPL
  "Manchester United": ["Man Utd", "Man United", "MUFC", "Manchester Utd"]
  "Manchester City": ["Man City", "MCFC", "Manchester C"]
  "Liverpool": ["Liverpool FC", "LFC"]
  "Arsenal": ["Arsenal FC", "AFC"]
  "Chelsea": ["Chelsea FC", "CFC"]
  "Tottenham Hotspur": ["Tottenham", "Spurs", "THFC"]
  "Newcastle United": ["Newcastle", "Newcastle Utd", "NUFC"]
  "West Ham United": ["West Ham", "West Ham Utd", "WHU"]
  "Aston Villa": ["Villa", "AVFC"]
  "Brighton and Hove Albion": ["Brighton", "Brighton Hove Albion", "BHAFC"]
  "Wolverhampton Wanderers": ["Wolves", "Wolverhampton"]
  "Crystal Palace": ["Palace", "CPFC"]
  "Everton": ["Everton FC", "EFC"]
  "Fulham": ["Fulham FC", "FFC"]
  "Bournemouth": ["AFC Bournemouth"]
  "Nottingham Forest": ["Nott'm Forest", "Forest", "NFFC"]
  "Leicester City": ["Leicester"]
  "Ipswich Town": ["Ipswich"]
  "Southampton": ["Southampton FC"]
  "Brentford": ["Brentford FC"]

  # La Liga
  "Real Madrid": ["Real Madrid CF"]
  "FC Barcelona": ["Barcelona", "Barca"]
  "Atletico Madrid": ["Atletico", "Atlético Madrid", "Atlético"]
  "Real Sociedad": ["Sociedad"]
  "Real Betis": ["Betis"]
  "Athletic Bilbao": ["Athletic Club", "Athletic"]
  "Villarreal": ["Villarreal CF"]
  "Sevilla": ["Sevilla FC"]
  "Valencia": ["Valencia CF"]
  "Girona": ["Girona FC"]

  # Bundesliga
  "Bayern Munich": ["Bayern München", "FC Bayern", "Bayern"]
  "Borussia Dortmund": ["Dortmund", "BVB"]
  "RB Leipzig": ["Leipzig", "RasenBallsport Leipzig"]
  "Bayer Leverkusen": ["Leverkusen", "Bayer 04"]
  "Eintracht Frankfurt": ["Frankfurt", "SGE"]
  "VfB Stuttgart": ["Stuttgart"]
  "Borussia Monchengladbach": ["Gladbach", "Mönchengladbach", "BMG"]
  "VfL Wolfsburg": ["Wolfsburg"]
  "SC Freiburg": ["Freiburg"]
  "TSG Hoffenheim": ["Hoffenheim"]

  # Serie A
  "Inter Milan": ["Inter", "Internazionale", "FC Internazionale"]
  "AC Milan": ["Milan"]
  "Juventus": ["Juventus FC", "Juve"]
  "SSC Napoli": ["Napoli"]
  "AS Roma": ["Roma"]
  "SS Lazio": ["Lazio"]
  "Atalanta": ["Atalanta BC"]
  "ACF Fiorentina": ["Fiorentina"]
  "Bologna": ["Bologna FC"]
  "Torino": ["Torino FC"]

  # Champions League extras (covered above mostly)
  "Paris Saint-Germain": ["PSG", "Paris SG"]
  "Benfica": ["SL Benfica"]
  "Porto": ["FC Porto"]
  "Sporting CP": ["Sporting Lisbon", "Sporting"]
  "Ajax": ["AFC Ajax"]
  "Club Brugge": ["Brugge"]
  "Celtic": ["Celtic FC"]
  "Red Bull Salzburg": ["Salzburg", "RB Salzburg"]

basketball:
  # NBA
  "Los Angeles Lakers": ["LA Lakers", "Lakers", "LAL"]
  "Los Angeles Clippers": ["LA Clippers", "Clippers", "LAC"]
  "Golden State Warriors": ["Warriors", "GSW", "GS Warriors"]
  "Boston Celtics": ["Celtics", "BOS"]
  "Milwaukee Bucks": ["Bucks", "MIL"]
  "Denver Nuggets": ["Nuggets", "DEN"]
  "Philadelphia 76ers": ["Sixers", "76ers", "PHI"]
  "Phoenix Suns": ["Suns", "PHX"]
  "Miami Heat": ["Heat", "MIA"]
  "Dallas Mavericks": ["Mavericks", "Mavs", "DAL"]
  "New York Knicks": ["Knicks", "NYK"]
  "Brooklyn Nets": ["Nets", "BKN"]
  "Cleveland Cavaliers": ["Cavaliers", "Cavs", "CLE"]
  "Oklahoma City Thunder": ["Thunder", "OKC"]
  "Minnesota Timberwolves": ["Timberwolves", "Wolves", "MIN"]
  "Sacramento Kings": ["Kings", "SAC"]
  "New Orleans Pelicans": ["Pelicans", "NOP"]
  "Indiana Pacers": ["Pacers", "IND"]
  "Orlando Magic": ["Magic", "ORL"]
  "Memphis Grizzlies": ["Grizzlies", "MEM"]
  "Atlanta Hawks": ["Hawks", "ATL"]
  "Chicago Bulls": ["Bulls", "CHI"]
  "Houston Rockets": ["Rockets", "HOU"]
  "Toronto Raptors": ["Raptors", "TOR"]
  "Portland Trail Blazers": ["Trail Blazers", "Blazers", "POR"]
  "San Antonio Spurs": ["Spurs", "SAS"]
  "Utah Jazz": ["Jazz", "UTA"]
  "Charlotte Hornets": ["Hornets", "CHA"]
  "Detroit Pistons": ["Pistons", "DET"]
  "Washington Wizards": ["Wizards", "WAS"]

  # Euroleague
  "Real Madrid Baloncesto": ["Real Madrid", "Real Madrid Basketball"]
  "FC Barcelona Basquet": ["Barcelona", "Barca Basketball"]
  "Olympiacos BC": ["Olympiacos", "Olympiakos"]
  "Panathinaikos BC": ["Panathinaikos"]
  "Fenerbahce": ["Fenerbahçe", "Fenerbahce Beko"]
  "Anadolu Efes": ["Efes"]
  "CSKA Moscow": ["CSKA"]
  "Maccabi Tel Aviv": ["Maccabi"]
  "Partizan Belgrade": ["Partizan"]
  "Virtus Bologna": ["Virtus"]
